### ISSUE TITLE
Support 2023.1

### ISSUE THREAD

**Issue by PikachuEXE** [crosscode-nl/x509certbuddy#1]
I am using RubyMine and 2023.1 is released
I wonder if the Compatibility Range requires manual update from author or Jetbrains or automatically

**Comment by crosscode-nl** [comment]
Thanks for reporting this issue. I scheduled a new release which should add support for this version. It will be available in a few days once Jetbrains has approved the plugin. Let me know once version 0.6 is available if it solves your problem. :)

**Comment by PikachuEXE** [comment]
Updated RubyMine & the plugin and everything seems fine

**Comment by PikachuEXE** [comment]
2023.2 is available now

**Comment by crosscode-nl** [comment]
Updated plugin will be available after review by JetBrains (1-2 days). Thanks for notifying.
